export type UltronAgent = "CORTEX" | "SPECTER" | "STRIKER" | "PULSE" | "SENTINEL";

export interface Agent {
  id: string;
  name: string;
  oneLiner: string;
  description: string;
  replaces: string;
  replaceCost: string;
  tools: string[];
  exampleOutput: string;
  connectedTo: string[];
  ultronAgent: UltronAgent;
}

export interface Department {
  id: string;
  name: string;
  icon: string;
  agents: Agent[];
}

export const departments: Department[] = [
  {
    id: "sales",
    name: "sales",
    icon: "folder",
    agents: [
      {
        id: "lead-finder",
        name: "lead-finder",
        oneLiner: "Finds companies matching your ICP daily",
        description: "Scans the web, LinkedIn, and industry databases every morning to find companies that match your ideal customer profile. Surfaces new prospects before your competitors even know they exist.",
        replaces: "SDR (prospecting hours)",
        replaceCost: "$4,500/mo",
        tools: ["Brave Search", "Apollo", "LinkedIn"],
        exampleOutput: "Found: Marcus Weber, AutomateDE, Score: 85/100, Signal: posted about scaling bottlenecks 3 days ago",
        connectedTo: ["lead-scorer", "prospect-researcher"],
        ultronAgent: "SPECTER",
      },
      {
        id: "lead-scorer",
        name: "lead-scorer",
        oneLiner: "Scores every lead 0-100 based on fit and timing signals",
        description: "Analyzes company size, tech stack, funding stage, hiring patterns, and social signals to score leads. Prioritizes who to contact first so you never waste time on bad fits.",
        replaces: "Sales Analyst",
        replaceCost: "$3,800/mo",
        tools: ["Apollo", "Brave Search", "Internal DB"],
        exampleOutput: "Score: 92/100 | Fit: Enterprise SaaS, 50-200 employees | Signal: Hiring 3 ops roles, CEO posted about 'drowning in manual work'",
        connectedTo: ["lead-finder", "email-writer"],
        ultronAgent: "SPECTER",
      },
      {
        id: "email-writer",
        name: "email-writer",
        oneLiner: "Drafts personalized cold emails referencing prospect's actual activity",
        description: "Writes cold emails that reference the prospect's recent posts, company news, and pain points. Every email is unique. No templates, no generic pitches.",
        replaces: "SDR (email writing)",
        replaceCost: "$4,500/mo",
        tools: ["Gmail", "Apollo", "Brave Search"],
        exampleOutput: "Subject: 'Saw your post about scaling ops'\nHi Marcus, noticed you mentioned bottlenecks in your Leipzig team. We automated exactly that for a similar company last month...",
        connectedTo: ["lead-scorer", "follow-up-engine"],
        ultronAgent: "STRIKER",
      },
      {
        id: "follow-up-engine",
        name: "follow-up-engine",
        oneLiner: "Sends follow-ups on day 3, 7, 14 automatically",
        description: "Tracks every sent email and triggers follow-ups at optimal intervals. Adjusts tone and angle with each touch. Stops automatically when a reply is detected.",
        replaces: "SDR (follow-up time)",
        replaceCost: "$4,500/mo",
        tools: ["Gmail", "Calendar", "Internal DB"],
        exampleOutput: "Follow-up #2 (Day 7): 'Quick thought on your ops scaling' | Tone: lighter, added case study link | Status: Scheduled for Tuesday 9:14 AM",
        connectedTo: ["email-writer", "inbox-triager"],
        ultronAgent: "STRIKER",
      },
      {
        id: "inbox-triager",
        name: "inbox-triager",
        oneLiner: "Scans email for deal signals, flags opportunities, deprioritizes noise",
        description: "Reads every incoming email, categorizes by intent (interested, objection, referral, spam), and surfaces only what matters. You start each day knowing exactly what needs attention.",
        replaces: "Executive Assistant",
        replaceCost: "$3,200/mo",
        tools: ["Gmail", "Telegram", "Internal DB"],
        exampleOutput: "PRIORITY: Reply from Marcus Weber (AutomateDE) | Intent: Interested | Key quote: 'Can we see a demo this week?' | Action: Flag for immediate response",
        connectedTo: ["follow-up-engine", "pipeline-tracker"],
        ultronAgent: "SENTINEL",
      },
      {
        id: "pipeline-tracker",
        name: "pipeline-tracker",
        oneLiner: "Tracks every deal stage, alerts on stale conversations",
        description: "Maintains a live pipeline view. Moves deals between stages based on email activity. Alerts you when conversations go cold so nothing falls through the cracks.",
        replaces: "CRM Manager",
        replaceCost: "$3,500/mo",
        tools: ["Internal DB", "Telegram", "Calendar"],
        exampleOutput: "ALERT: 3 deals stale >7 days | AutomateDE moved to 'Demo Scheduled' | Pipeline value: $42,500 | Close rate trending: 23% (up from 18%)",
        connectedTo: ["inbox-triager", "meeting-prepper"],
        ultronAgent: "SENTINEL",
      },
    ],
  },
  {
    id: "content",
    name: "content",
    icon: "folder",
    agents: [
      {
        id: "trend-researcher",
        name: "trend-researcher",
        oneLiner: "Scans LinkedIn, Twitter, Reddit for what's working in your niche",
        description: "Monitors social platforms daily for trending topics, viral formats, and engagement patterns in your industry. Surfaces what to talk about before everyone else does.",
        replaces: "Content Researcher",
        replaceCost: "$3,000/mo",
        tools: ["Brave Search", "LinkedIn", "Reddit API"],
        exampleOutput: "Trending in AI SaaS: 'agent vs copilot' debate (847 engagements in 48h) | Top format: contrarian hot take + screenshot proof | Recommended angle: your actual agent logs",
        connectedTo: ["content-creator", "hook-analyzer"],
        ultronAgent: "CORTEX",
      },
      {
        id: "content-creator",
        name: "content-creator",
        oneLiner: "Writes posts in your voice across every platform",
        description: "Generates platform-native content: LinkedIn articles, Twitter threads, Instagram captions. Trained on your writing style so every post sounds like you, not a bot.",
        replaces: "Content Writer",
        replaceCost: "$4,000/mo",
        tools: ["Internal DB", "LinkedIn", "Twitter API"],
        exampleOutput: "LinkedIn post: 'I replaced my SDR with an AI agent 3 months ago. Here's what actually happened (with real numbers):' [Thread: 7 slides, estimated reach: 12K]",
        connectedTo: ["trend-researcher", "content-scheduler"],
        ultronAgent: "PULSE",
      },
      {
        id: "hook-analyzer",
        name: "hook-analyzer",
        oneLiner: "Extracts viral patterns from top performing posts",
        description: "Analyzes the first lines, structures, and formats of your best-performing content and competitors' viral posts. Gives you proven hooks to use in your next piece.",
        replaces: "Social Media Strategist",
        replaceCost: "$3,500/mo",
        tools: ["Brave Search", "LinkedIn", "Internal DB"],
        exampleOutput: "Top hook pattern this week: 'I [did unexpected thing]. [Time period] later, here's what happened:' | Used by 4/10 viral posts in your niche | Your last post using this pattern: 3.2x avg engagement",
        connectedTo: ["trend-researcher", "content-creator"],
        ultronAgent: "CORTEX",
      },
      {
        id: "content-scheduler",
        name: "content-scheduler",
        oneLiner: "Blocks posting slots on Calendar, maintains publishing cadence",
        description: "Manages your content calendar across all platforms. Books posting slots, ensures consistent cadence, and prevents gaps. You never miss a posting window.",
        replaces: "Social Media Manager",
        replaceCost: "$3,200/mo",
        tools: ["Calendar", "Internal DB", "Telegram"],
        exampleOutput: "This week: Mon 8:30 AM LinkedIn (thought leadership), Wed 12 PM Twitter thread (case study), Fri 9 AM LinkedIn (contrarian take) | All drafted and queued",
        connectedTo: ["content-creator", "engagement-tracker"],
        ultronAgent: "PULSE",
      },
      {
        id: "engagement-tracker",
        name: "engagement-tracker",
        oneLiner: "Monitors post performance, identifies what to double down on",
        description: "Tracks likes, comments, shares, and profile visits for every piece of content. Identifies patterns in what resonates so you can produce more of what works.",
        replaces: "Analytics Manager",
        replaceCost: "$3,000/mo",
        tools: ["LinkedIn", "Twitter API", "Internal DB"],
        exampleOutput: "Weekly report: LinkedIn +340% reach | Top post: agent logs thread (14.2K impressions) | Pattern: posts with real screenshots get 4x engagement | Recommendation: more behind-the-scenes content",
        connectedTo: ["content-scheduler", "trend-researcher"],
        ultronAgent: "PULSE",
      },
    ],
  },
  {
    id: "outreach",
    name: "outreach",
    icon: "folder",
    agents: [
      {
        id: "prospect-researcher",
        name: "prospect-researcher",
        oneLiner: "Deep dives on every prospect before contact: company, role, recent posts, pain points",
        description: "Before you reach out to anyone, this agent builds a complete profile: company details, the person's role, their recent social posts, and inferred pain points. You never go in blind.",
        replaces: "Research Assistant",
        replaceCost: "$2,800/mo",
        tools: ["Brave Search", "Apollo", "LinkedIn"],
        exampleOutput: "PROFILE: Sarah Chen, VP Ops at ScaleFlow (Series B, $12M raised) | Recent: Posted about 'hiring fatigue' | Pain: scaling ops without headcount | Best angle: automation ROI",
        connectedTo: ["lead-finder", "dm-writer"],
        ultronAgent: "CORTEX",
      },
      {
        id: "contact-finder",
        name: "contact-finder",
        oneLiner: "Pulls verified emails and LinkedIn profiles via Apollo",
        description: "Finds and verifies contact information for every prospect. Cross-references multiple sources to ensure you have working emails and the right LinkedIn profiles.",
        replaces: "Data Entry / SDR",
        replaceCost: "$2,500/mo",
        tools: ["Apollo", "Brave Search", "LinkedIn"],
        exampleOutput: "sarah.chen@scaleflow.io (verified, 98% confidence) | LinkedIn: /in/sarahchen-ops | Also found: Direct report Tom Liu, Head of Automation",
        connectedTo: ["prospect-researcher", "campaign-builder"],
        ultronAgent: "SPECTER",
      },
      {
        id: "dm-writer",
        name: "dm-writer",
        oneLiner: "Drafts personalized DMs for LinkedIn, Twitter, Instagram",
        description: "Crafts short, personalized direct messages for each platform. References the prospect's recent activity to feel genuine, not templated. Adjusts tone per platform norms.",
        replaces: "SDR (DM outreach)",
        replaceCost: "$4,500/mo",
        tools: ["LinkedIn", "Twitter API", "Internal DB"],
        exampleOutput: "LinkedIn DM: 'Sarah, your post about hiring fatigue hit home. We helped a similar Series B cut their ops team needs by 60% with AI agents. Happy to share the playbook if useful.'",
        connectedTo: ["prospect-researcher", "response-handler"],
        ultronAgent: "STRIKER",
      },
      {
        id: "campaign-builder",
        name: "campaign-builder",
        oneLiner: "Builds multi-touch outreach sequences with timing logic",
        description: "Creates full outreach campaigns: email on day 1, LinkedIn connect on day 2, follow-up on day 4, DM on day 7. Each touch builds on the last with different angles.",
        replaces: "Campaign Manager",
        replaceCost: "$4,000/mo",
        tools: ["Gmail", "LinkedIn", "Calendar", "Internal DB"],
        exampleOutput: "Campaign 'ScaleFlow': Touch 1 (Email, Day 0) > Touch 2 (LinkedIn connect, Day 1) > Touch 3 (Email follow-up, Day 4) > Touch 4 (LinkedIn DM, Day 7) | Status: Active, 3/4 touches sent",
        connectedTo: ["contact-finder", "response-handler"],
        ultronAgent: "STRIKER",
      },
      {
        id: "response-handler",
        name: "response-handler",
        oneLiner: "Categorizes replies: interested, objection, not now, dead",
        description: "Reads every reply across email and DMs. Categorizes intent instantly: hot lead, soft objection, timing issue, or dead end. Routes hot leads to you immediately via Telegram.",
        replaces: "SDR (response management)",
        replaceCost: "$4,500/mo",
        tools: ["Gmail", "LinkedIn", "Telegram", "Internal DB"],
        exampleOutput: "NEW REPLY from Sarah Chen | Category: INTERESTED | Key quote: 'This sounds relevant, can you send a case study?' | Action: Auto-sent case study PDF, flagged for personal follow-up",
        connectedTo: ["dm-writer", "campaign-builder", "pipeline-tracker"],
        ultronAgent: "SENTINEL",
      },
    ],
  },
  {
    id: "research",
    name: "research",
    icon: "folder",
    agents: [
      {
        id: "competitor-monitor",
        name: "competitor-monitor",
        oneLiner: "Checks competitor websites, pricing, features, job postings daily",
        description: "Visits competitor sites every day looking for changes: new features, pricing updates, messaging shifts, and job postings that reveal strategy. You always know what they are doing.",
        replaces: "Competitive Intelligence Analyst",
        replaceCost: "$4,200/mo",
        tools: ["Brave Search", "Internal DB", "Telegram"],
        exampleOutput: "CHANGE DETECTED: CompetitorX updated pricing page | New enterprise tier at $299/mo (was $199) | Also: 3 new job postings for 'AI Engineer' | Signal: they're investing heavily in AI features",
        connectedTo: ["market-scanner", "opportunity-detector"],
        ultronAgent: "CORTEX",
      },
      {
        id: "market-scanner",
        name: "market-scanner",
        oneLiner: "Tracks industry trends, funding rounds, product launches",
        description: "Monitors tech news, Crunchbase, and industry publications for market movements. Surfaces funding rounds, acquisitions, and product launches that affect your competitive landscape.",
        replaces: "Market Research Analyst",
        replaceCost: "$3,800/mo",
        tools: ["Brave Search", "Internal DB", "Telegram"],
        exampleOutput: "FUNDING: ScaleFlow raised $12M Series B (relevant: they are in your ICP) | LAUNCH: CompetitorY released API v2 | TREND: 'AI agent' mentions up 340% in SaaS Twitter this month",
        connectedTo: ["competitor-monitor", "opportunity-detector"],
        ultronAgent: "CORTEX",
      },
      {
        id: "customer-researcher",
        name: "customer-researcher",
        oneLiner: "Builds deep profiles on prospects before sales calls",
        description: "Before any sales call, this agent compiles everything: the prospect's company background, recent news, the person's career history, social posts, and mutual connections. You walk in prepared.",
        replaces: "Research Assistant",
        replaceCost: "$2,800/mo",
        tools: ["Brave Search", "Apollo", "LinkedIn"],
        exampleOutput: "PRE-CALL BRIEF: Meeting with Sarah Chen, ScaleFlow | Company: B2B SaaS, 87 employees, Series B | Her focus: scaling ops without headcount | Recent: Spoke at SaaStr about 'lean teams' | Mutual: Connected to 3 of your clients",
        connectedTo: ["prospect-researcher", "meeting-prepper"],
        ultronAgent: "CORTEX",
      },
      {
        id: "review-miner",
        name: "review-miner",
        oneLiner: "Scans G2, Trustpilot, Reddit for competitor complaints",
        description: "Monitors review sites and forums for competitor complaints. Categorizes by theme (pricing, support, features, reliability) and surfaces the most common pain points you can use in your positioning.",
        replaces: "Market Research Analyst",
        replaceCost: "$3,800/mo",
        tools: ["Brave Search", "Reddit API", "Internal DB"],
        exampleOutput: "CompetitorX negative reviews (last 30 days): 12 new | Top complaints: 'Support takes 5+ days' (7 mentions), 'Pricing increased without notice' (4 mentions) | Opportunity: position on support speed",
        connectedTo: ["competitor-monitor", "content-creator"],
        ultronAgent: "CORTEX",
      },
      {
        id: "opportunity-detector",
        name: "opportunity-detector",
        oneLiner: "Flags trigger events: new funding, leadership changes, product gaps",
        description: "Watches for trigger events that signal buying intent: companies that just raised funding, hired a new VP of Ops, or posted about scaling challenges. These are your warmest leads.",
        replaces: "Business Development Rep",
        replaceCost: "$4,500/mo",
        tools: ["Brave Search", "Apollo", "LinkedIn", "Internal DB"],
        exampleOutput: "TRIGGER: NovaTech just hired VP of Operations (signal: scaling) | TRIGGER: DataBridge CEO posted 'we need to automate or die' | TRIGGER: CloudBase raised $8M (signal: growth phase) | 3 new warm leads added",
        connectedTo: ["market-scanner", "lead-finder"],
        ultronAgent: "SPECTER",
      },
    ],
  },
  {
    id: "monitoring",
    name: "monitoring",
    icon: "folder",
    agents: [
      {
        id: "uptime-checker",
        name: "uptime-checker",
        oneLiner: "Monitors website health every 6 hours",
        description: "Checks your website, landing pages, and key URLs on a regular schedule. Alerts you immediately via Telegram if anything goes down so you can fix it before customers notice.",
        replaces: "DevOps Engineer (partial)",
        replaceCost: "$6,000/mo",
        tools: ["Brave Search", "Telegram", "Internal DB"],
        exampleOutput: "CHECK: work.51ultron.com | Status: 200 OK | Response time: 342ms | SSL: Valid (expires in 47 days) | Last downtime: None in 30 days",
        connectedTo: ["ssl-watcher", "performance-auditor"],
        ultronAgent: "SENTINEL",
      },
      {
        id: "ssl-watcher",
        name: "ssl-watcher",
        oneLiner: "Tracks certificate expiry, alerts 14 days before",
        description: "Monitors SSL certificates across all your domains. Sends alerts at 30, 14, and 7 days before expiry. No more surprise certificate expirations killing your site.",
        replaces: "SysAdmin (partial)",
        replaceCost: "$5,000/mo",
        tools: ["Brave Search", "Telegram", "Internal DB"],
        exampleOutput: "SSL CHECK: work.51ultron.com | Certificate: Valid | Issuer: Let's Encrypt | Expires: April 22, 2026 (47 days) | Status: No action needed",
        connectedTo: ["uptime-checker", "security-scanner"],
        ultronAgent: "SENTINEL",
      },
      {
        id: "performance-auditor",
        name: "performance-auditor",
        oneLiner: "Measures page speed, finds broken links, checks mobile UX",
        description: "Runs performance audits on your site: page load times, broken links, mobile responsiveness, and Core Web Vitals. Surfaces issues that hurt your conversion rates.",
        replaces: "QA Engineer (partial)",
        replaceCost: "$5,500/mo",
        tools: ["Brave Search", "Internal DB", "Telegram"],
        exampleOutput: "AUDIT: /pricing page | Load time: 2.1s (target: <2s) | Broken links: 1 (/old-blog-post) | Mobile score: 94/100 | Recommendation: Compress hero image (-340KB)",
        connectedTo: ["uptime-checker", "api-health-monitor"],
        ultronAgent: "SENTINEL",
      },
      {
        id: "security-scanner",
        name: "security-scanner",
        oneLiner: "Checks for exposed endpoints, dependency vulnerabilities",
        description: "Scans your public-facing infrastructure for common security issues: exposed admin panels, outdated dependencies, open ports, and misconfigured headers. Catches problems before bad actors do.",
        replaces: "Security Engineer (partial)",
        replaceCost: "$7,000/mo",
        tools: ["Brave Search", "Internal DB", "Telegram"],
        exampleOutput: "SCAN: No critical vulnerabilities found | Note: X-Frame-Options header missing on /api/docs | Recommendation: Add security headers | Last full scan: 6 hours ago",
        connectedTo: ["ssl-watcher", "api-health-monitor"],
        ultronAgent: "SENTINEL",
      },
      {
        id: "api-health-monitor",
        name: "api-health-monitor",
        oneLiner: "Tests every API endpoint response time and availability",
        description: "Hits your API endpoints on a schedule to verify they respond correctly and within acceptable time limits. Detects degraded performance before it impacts users.",
        replaces: "DevOps Engineer (partial)",
        replaceCost: "$6,000/mo",
        tools: ["Internal DB", "Telegram", "Brave Search"],
        exampleOutput: "API HEALTH: 12/12 endpoints healthy | Slowest: /api/reports (890ms, threshold: 1000ms) | Fastest: /api/health (45ms) | Errors last 24h: 0",
        connectedTo: ["performance-auditor", "security-scanner"],
        ultronAgent: "SENTINEL",
      },
    ],
  },
  {
    id: "operations",
    name: "operations",
    icon: "folder",
    agents: [
      {
        id: "morning-briefer",
        name: "morning-briefer",
        oneLiner: "Compiles overnight activity into a daily Telegram summary",
        description: "Every morning, this agent compiles everything that happened overnight: new leads found, emails sent, replies received, content performance, and monitoring alerts. One message, everything you need.",
        replaces: "Executive Assistant",
        replaceCost: "$3,200/mo",
        tools: ["Telegram", "Internal DB", "Gmail"],
        exampleOutput: "MORNING BRIEF | New leads: 4 | Emails sent: 12 | Replies: 2 (1 interested) | Content: LinkedIn post hit 8.4K impressions | Alerts: None | Pipeline: $42.5K active",
        connectedTo: ["weekly-reporter", "pipeline-tracker"],
        ultronAgent: "CORTEX",
      },
      {
        id: "weekly-reporter",
        name: "weekly-reporter",
        oneLiner: "Generates weekly metrics report across all departments",
        description: "Every Friday, compiles a full metrics report: leads generated, deals progressed, content performance, outreach results, and system health. Your entire business in one report.",
        replaces: "Operations Manager",
        replaceCost: "$5,000/mo",
        tools: ["Internal DB", "Telegram", "Gmail"],
        exampleOutput: "WEEKLY REPORT | Leads: 28 found, 19 scored >70 | Outreach: 84 emails, 12 replies (14.3% rate) | Content: 5 posts, 34K impressions | Deals: 2 moved to proposal | Revenue impact: $18.5K pipeline added",
        connectedTo: ["morning-briefer", "engagement-tracker"],
        ultronAgent: "CORTEX",
      },
      {
        id: "client-onboarder",
        name: "client-onboarder",
        oneLiner: "Runs new client onboarding sequence: research, emails, calendar, monitoring",
        description: "When a new client signs up, this agent kicks off the full sequence: researches their business, sends welcome emails, books kickoff calls, and sets up monitoring. No manual checklist needed.",
        replaces: "Customer Success Manager",
        replaceCost: "$4,500/mo",
        tools: ["Gmail", "Calendar", "Brave Search", "Internal DB"],
        exampleOutput: "ONBOARDING: ScaleFlow (new client) | Research: Complete | Welcome email: Sent | Kickoff call: Booked for Thursday 2 PM | Monitoring: Website + API checks active | Status: 4/4 steps complete",
        connectedTo: ["meeting-prepper", "uptime-checker"],
        ultronAgent: "STRIKER",
      },
      {
        id: "invoice-tracker",
        name: "invoice-tracker",
        oneLiner: "Monitors payments, flags overdue invoices, drafts reminders",
        description: "Tracks every invoice status. When payments go overdue, it drafts polite reminder emails at day 3, 7, and 14. Escalates to you only when personal intervention is needed.",
        replaces: "Bookkeeper / AR Clerk",
        replaceCost: "$2,800/mo",
        tools: ["Gmail", "Internal DB", "Telegram"],
        exampleOutput: "INVOICE STATUS | Paid: 8 ($34,200) | Pending: 3 ($12,500) | Overdue: 1 (DataBridge, $4,500, 5 days late) | Action: Reminder #1 sent automatically | Escalation: Not yet needed",
        connectedTo: ["weekly-reporter", "morning-briefer"],
        ultronAgent: "SENTINEL",
      },
      {
        id: "meeting-prepper",
        name: "meeting-prepper",
        oneLiner: "Researches attendees before every calendar event, delivers call briefs",
        description: "Before every meeting on your calendar, this agent researches each attendee: their role, company, recent activity, and your history with them. Delivers a brief 30 minutes before the call.",
        replaces: "Executive Assistant",
        replaceCost: "$3,200/mo",
        tools: ["Calendar", "Brave Search", "Apollo", "Telegram"],
        exampleOutput: "CALL BRIEF (30 min before) | Meeting: ScaleFlow Demo | Attendees: Sarah Chen (VP Ops), Tom Liu (Head of Automation) | Context: Sarah replied to cold email, interested in ops automation | Prep: She values data, lead with ROI numbers",
        connectedTo: ["customer-researcher", "pipeline-tracker"],
        ultronAgent: "CORTEX",
      },
    ],
  },
  {
    id: "growth",
    name: "growth",
    icon: "folder",
    agents: [
      {
        id: "referral-tracker",
        name: "referral-tracker",
        oneLiner: "Monitors referral links, tracks conversions, rewards referrers",
        description: "Tracks every referral link across your user base. Monitors who is sharing, which links convert, and automatically triggers reward notifications when referrals convert to paying customers.",
        replaces: "Growth Marketing Manager",
        replaceCost: "$4,500/mo",
        tools: ["Internal DB", "Gmail", "Telegram"],
        exampleOutput: "REFERRAL: Marcus Weber shared link (3 clicks, 1 signup) | Top referrer this month: Sarah Chen (5 referrals, 2 converted) | Reward triggered: $50 credit applied to Sarah's account",
        connectedTo: ["churn-detector", "upsell-spotter"],
        ultronAgent: "PULSE",
      },
      {
        id: "churn-detector",
        name: "churn-detector",
        oneLiner: "Flags accounts with declining usage before they cancel",
        description: "Monitors login frequency, feature usage, and support tickets for every account. Flags users showing churn signals so you can intervene with a personal touch before they hit cancel.",
        replaces: "Customer Success Manager",
        replaceCost: "$4,500/mo",
        tools: ["Internal DB", "Telegram", "Gmail"],
        exampleOutput: "CHURN RISK: DataBridge | Signals: No login in 12 days, support ticket unresolved, usage down 60% | Risk score: HIGH (82/100) | Recommended action: Personal email from founder + expedite support ticket",
        connectedTo: ["referral-tracker", "upsell-spotter"],
        ultronAgent: "SENTINEL",
      },
      {
        id: "upsell-spotter",
        name: "upsell-spotter",
        oneLiner: "Identifies free users hitting limits who are ready to upgrade",
        description: "Watches usage patterns for users approaching plan limits: API calls, agent runs, team seats. Surfaces the warmest upgrade candidates so you can reach out at the perfect moment.",
        replaces: "Revenue Operations",
        replaceCost: "$4,000/mo",
        tools: ["Internal DB", "Gmail", "Telegram"],
        exampleOutput: "UPSELL READY: NovaTech (Free plan) | Usage: 92% of agent run limit | Growth: Added 3 team members this week | Trigger: Hit API limit twice yesterday | Recommended: Send upgrade nudge with ROI data",
        connectedTo: ["churn-detector", "referral-tracker"],
        ultronAgent: "SPECTER",
      },
      {
        id: "partnership-builder",
        name: "partnership-builder",
        oneLiner: "Drafts partnership proposals for complementary platforms",
        description: "Identifies complementary SaaS products, researches their partnership programs, and drafts tailored proposals highlighting mutual value. Opens doors to co-marketing and integration partnerships.",
        replaces: "Business Development Manager",
        replaceCost: "$5,000/mo",
        tools: ["Brave Search", "Gmail", "LinkedIn", "Internal DB"],
        exampleOutput: "PARTNERSHIP MATCH: IntegrateHQ (CRM platform, 5K users) | Overlap: 34% ICP match | Proposal drafted: Co-webinar on 'AI agents + CRM' | Contact: partnerships@integratehq.com (verified)",
        connectedTo: ["market-scanner", "launch-coordinator"],
        ultronAgent: "STRIKER",
      },
      {
        id: "launch-coordinator",
        name: "launch-coordinator",
        oneLiner: "Orchestrates product launches across all departments simultaneously",
        description: "When you launch a new feature or product, this agent coordinates every department: content team writes announcements, outreach targets relevant prospects, monitoring watches for issues, and operations tracks results.",
        replaces: "Product Marketing Manager",
        replaceCost: "$5,500/mo",
        tools: ["Internal DB", "Gmail", "Telegram", "Calendar"],
        exampleOutput: "LAUNCH: 'Ultron v2.0' | Status: 6/8 tasks complete | Content: 3 posts scheduled | Outreach: 150 targeted emails queued | Monitoring: Enhanced checks active | Missing: Press release review, Partner notifications",
        connectedTo: ["partnership-builder", "content-scheduler", "campaign-builder"],
        ultronAgent: "PULSE",
      },
    ],
  },
];

export const totalAgents = departments.reduce((sum, d) => sum + d.agents.length, 0);
export const totalDepartments = departments.length;

export const ultronMapping: { label: string; departments: string; agents: string; color: string }[] = [
  { label: "SPECTER + STRIKER", departments: "sales/ + outreach/", agents: "Lead generation, scoring, email, DMs, campaigns, follow-ups", color: "#DA4E24" },
  { label: "PULSE", departments: "content/", agents: "Trend research, content creation, scheduling, engagement tracking", color: "#DA4E24" },
  { label: "CORTEX", departments: "research/", agents: "Competitor monitoring, market scanning, customer research, opportunity detection", color: "#DA4E24" },
  { label: "SENTINEL", departments: "monitoring/", agents: "Uptime, SSL, performance, security, API health", color: "#DA4E24" },
  { label: "ALL 5", departments: "operations/ + growth/", agents: "Morning briefs, reports, onboarding, churn detection, launches", color: "#DA4E24" },
];
